[package]
name = "vst3_macro"
version = "0.1.0"
edition = "2024"

[dependencies]
proc-macro2 = "1.0.86"
quote = "1.0.37"
syn = { version = "2.0.77", features = ["full"] }
log.workspace = true

[lib]
proc-macro = true